# permissions for end users to view workflows.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: workflow
    app.kubernetes.io/managed-by: kustomize
  name: workflow-viewer-role
rules:
- apiGroups:
  - sky.my.domain
  resources:
  - workflows
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sky.my.domain
  resources:
  - workflows/status
  verbs:
  - get
