apiVersion: sky.my.domain/v1alpha1
kind: Workflow
metadata:
  labels:
    app.kubernetes.io/name: workflow
    app.kubernetes.io/managed-by: kustomize
  name: workflow-sample
spec:
  # TODO(user): Add fields here
